
question9 = Question.create(text: "¿Cuál es el plato típico para fechas patrias?", difficulty: 2, link_imagen: "https://www.eltucumano.com/fotos/cache/notas/2020/05/29/818x460_200529153032_53255.jpeg", levels_id: 18)
Answer.create(text: "Asado", correct: false, question: question9)
Answer.create(text: "Empanadas", correct: false, question: question9)
Answer.create(text: "Locro", correct: true, question: question9)
Answer.create(text: "Humita", correct: false, question: question9)

question10 = Question.create(text: "¿Cuál es el postre argentino hecho a base de dulce de leche y coco rallado?", difficulty: 1, link_imagen: "https://scm-assets.constant.co/scm/unilever/2bb5223be0548fcc55c230aa5f951219/ce65930b-bc22-4bf3-9aa8-1e6b2708f982.png", levels_id: 17)
Answer.create(text: "Pasta Frola", correct: false, question: question10)
Answer.create(text: "Alfajor de maicena", correct: false, question: question10)
Answer.create(text: "Panqueques con Dulce de Leche", correct: false, question: question10)
Answer.create(text: "Chocotorta", correct: true, question: question10)

question11 = Question.create(text: "¿Cuál es la bebida típica argentina al comer una picada?", difficulty: 3, link_imagen: "https://pbs.twimg.com/media/Bs3zY9jIEAAIqvy.jpg", levels_id: 19)
Answer.create(text: "Gancia", correct: true, question: question11)
Answer.create(text: "Fernet", correct: false, question: question11)
Answer.create(text: "Vino", correct: false, question: question11)
Answer.create(text: "Cerveza", correct: false, question: question11)

question12 = Question.create(text: "¿Cuál es la pasta típica argentina se come los 29 de cada mes?", difficulty: 2, link_imagen: "https://img-global.cpcdn.com/recipes/f5c0380ee753ee7b/680x482cq70/noquis-del-29-foto-principal.jpg", levels_id: 19)
Answer.create(text: "Fideos", correct: false, question: question12)
Answer.create(text: "Tallarines", correct: false, question: question12)
Answer.create(text: "Ñoquis", correct: true, question: question12)
Answer.create(text: "Ravioles", correct: false, question: question12)

question13 = Question.create(text: "¿Cuál es la bebida argentina hecha a base de frutas, vino y soda?", difficulty: 3, link_imagen: "https://img-global.cpcdn.com/recipes/59cc9c144671732a/400x400cq70/photo.jpg", levels_id: 20)
Answer.create(text: "Mojito", correct: false, question: question13)
Answer.create(text: "Caipirinha", correct: false, question: question13)
Answer.create(text: "Sangría", correct: true, question: question13)
Answer.create(text: "Piña colada", correct: false, question: question13)

question14 = Question.create(text: "¿Cuál es el plato típico argentino que consiste en una tarta rellena de carne picada, huevo duro y aceitunas?", difficulty: 1, link_imagen: "https://img-global.cpcdn.com/recipes/212bf10bd52132b5/1200x630cq70/photo.jpg", levels_id: 20)
Answer.create(text: "Milanesa", correct: false, question: question14)
Answer.create(text: "Empanada", correct: false, question: question14)
Answer.create(text: "Tarta de jamón y queso", correct: false, question: question14)
Answer.create(text: "Tarta de carne", correct: true, question: question14)