# frozen_string_literal: true

source 'https://rubygems.org'
gem 'rake'
gem 'sinatra-activerecord'
gem 'sqlite3'
gem 'sinatra-flash'
group :test do
  gem 'rack-test'
  gem 'rspec'
  gem 'simplecov', require: false, group: :test
end
github 'sinatra/sinatra' do
  gem 'sinatra'
  gem 'sinatra-contrib'
end
